### ISSUE TITLE
검색창 액티비티 완료시 코드 변경

### ISSUE THREAD

**Issue by sami355-24** [fit-trip/client#4]
https://github.com/fit-trip/client/blob/b22c23fa98c9e44e0136f60a1eb66a87cc61a3d8/app/src/main/java/com/example/fittrip/LoginActivity.kt#L18

RegisterActivity로 되어 있는걸 검색창 액티비티 이름으로 바꾸고 main에 머지 필요

**Comment by hw0603** [comment]
Resolved.
